framework:
    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    default_locale: en
    enabled_locales: ['en', 'fr']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
